spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/running-cat/dev-demo.git
          username:
          password:
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7000/eureka/
  instance:
    prefer-ip-address: true