server:
  port: 7020
spring:
  application:
    name: config
  profiles:
    active: @environment@
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS