server:
  port: 8003
spring:
  profiles:
    active: @environment@
  application:
    name: app-seckill
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: store.tacomall.common.db
  mapper-locations: classpath:/mapper/*Mapper.xml