spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: 123456
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://localhost:23000/tacomall?serverTimezone=Asia/Shanghai
  boot:
    admin:
      client:
        url: http://localhost:7030
        username: root
        password: 123456
        instance:
          prefer-ip: true
  redis:
    host: 127.0.0.1
    port: 20000
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7000/eureka/
  instance:
    prefer-ip-address: true