spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: 123456
          driver-class-name: com.p6spy.engine.spy.P6SpyDriver
          url: jdbc:p6spy:mysql://localhost:23000/tacomall?serverTimezone=Asia/Shanghai
  kafka:
    bootstrap-servers: 127.0.0.1:7002
    consumer:
      group-id: stream-in
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer