spring:
  boot:
    admin:
      client:
        url: http://localhost:7030
        username: root
        password: 123456
        instance:
          prefer-ip: true
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7000/eureka/
  instance:
    prefer-ip-address: true