server:
  port: 9000
spring:
  application:
    name: api-portal
  profiles:
    active: @environment@
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: store.tacomall.common.db
  mapper-locations: classpath:/mapper/*Mapper.xml, classpath*:/mapper/*Mapper.xml
wx:
  miniapp:
      appid: wx1492e33a9a6b64a3