spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tacomall?serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 7010
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7000/eureka/
