server:
  port: 9002
spring:
  application:
    name: api-merchant
  profiles:
    active: @environment@
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: store.tacomall.common.db
  mapper-locations: classpath:/mapper/*Mapper.xml